sudo: required
services:
  - docker
before_install:
  - docker build -t kashinath/dockerdemo -f Dockerfile.dev .
script:
  - docker run kashinath/dockerdemo npm run test -- --coverage

deploy:
  provider: elasticbenstalk
  region: "us-west-2"
  app: "dockerdemo"
  env: "Dockerdemo-env"
  bucket_name: "elasticbeanstalk-us-west-2-217294222127"
  bucket_path: "dockerdemo"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secrete_access_key: $AWS_SECRET_KEY
